apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rosa-hcp-metadata
spec:
  description: |
    The `rosa-hcp-metadata` task generates a unique name for an OpenShift cluster using a predefined prefix and a randomly generated hexadecimal string.
    The cluster name is generated to follow a specific pattern (`kx-<random-hex>`) where `kx` is the prefix and a 10-character random string ensures uniqueness.
    This task outputs the generated cluster name as a result, which can be used in subsequent steps or tasks within a Tekton pipeline.
    It ensures that each cluster created in different pipeline runs has a unique, non-colliding identifier.
  results:
    - name: cluster-name
      description: The generated name for the OpenShift cluster.
  steps:
    - name: generate-cluster-name
      image: registry.access.redhat.com/ubi9/openssl:9.1-2
      script: |
        #!/usr/bin/env bash
        set -o errexit
        set -o nounset
        set -o pipefail

        # Generate a unique cluster name using a prefix and a random hex string
        CLUSTER_NAME="kx-$( openssl rand -hex 5 )"
        
        # Output the cluster name to the specified result path
        echo -n "$CLUSTER_NAME" | tee $(results.cluster-name.path)
